export const INITIATE_ACTORS = "INITIATE_ACTORS";
export const SET_ACTORS = "SET_ACTORS";

export const GET_ACTOR_BY_ID = "GET_ACTOR_BY_ID";
export const SET_ACTOR_BY_ID = "SET_ACTOR_BY_ID";

export const CLEAR_ACTOR_DATA = "CLEAR_ACTOR_DATA";

export const INIT_SEARCH_ACTORS = "INIT_SEARCH_ACTORS";
export const SET_SEARCH_ACTORS = "SET_SEARCH_ACTORS";
