export const INIT_SEARCH_ACTORS = "INIT_SEARCH_ACTORS";
export const SET_SEARCH_ACTORS = "SET_SEARCH_ACTORS";
export const INIT_SEARCH_MOVIES = "INIT_SEARCH_MOVIES";
export const SET_SEARCH_MOVIES = "SET_SEARCH_MOVIES";
export const CLEAR_DATA = "CLEAR_DATA";
