export const INITIATE_MOVIES = "INITIATE_MOVIES";
export const SET_MOVIES = "SET_MOVIES";

export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const SET_MOVIE_BY_ID = "SET_MOVIE_BY_ID";

export const CLEAR_MOVIE_DATA = "CLEAR_MOVIE_DATA";

export const INIT_SEARCH_MOVIES = "INIT_SEARCH_MOVIES";
export const SET_SEARCH_MOVIES = "SET_SEARCH_MOVIES";
