export const INITIATE_MOVIES = "INITIATE_MOVIES";
export const SET_MOVIES = "SET_MOVIES";

export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const SET_MOVIE_BY_ID = "SET_MOVIE_BY_ID";

export const INITIATE_ACTORS = "INITIATE_ACTORS";
export const SET_ACTORS = "SET_ACTORS";

export const GET_ACTOR_BY_ID = "GET_ACTOR_BY_ID";
export const SET_ACTOR_BY_ID = "SET_ACTOR_BY_ID";

export const INIT_SEARCH_MOVIES = "INIT_SEARCH_MOVIES";
export const SET_SEARCH_MOVIES = "SET_SEARCH_MOVIES";
export const INIT_SEARCH_ACTORS = "INIT_SEARCH_ACTORS";
export const SET_SEARCH_ACTORS = "SET_SEARCH_ACTORS";
